# Generated by Django 5.1.2 on 2024-10-20 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('rate_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('room_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.roomcategory')),
            ],
        ),
    ]
